export enum ActivityAction {
  // ? REGISTER
  REGISTER_FAILED = 'REGISTER_FAILED',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',

  // ? LOGIN
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',
  LOGOUT = 'LOGOUT',
  LOGOUT_FROM_DEVICE = 'LOGOUT_FROM_DEVICE',
  LOGOUT_ALL = 'LOGOUT_ALL',
  REGISTER = 'REGISTER',

  // ? TOKEN
  TOKEN_REFRESH = 'TOKEN_REFRESH',
  TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS',
  TOKEN_REFRESH_FAILED = 'TOKEN_REFRESH_FAILED',

  // ? USER
  USER_CREATED = 'USER_CREATED',
  USER_UPDATED = 'USER_UPDATED',
  USER_DELETED = 'USER_DELETED',
  ASSIGN_PERMISSION_TO_USER_SUCCESS = 'ASSIGN_PERMISSION_TO_USER_SUCCESS',
  GET_USER_PERMISSIONS_SUCCESS = 'GET_USER_PERMISSIONS_SUCCESS',
  REMOVE_PERMISSION_FROM_USER_SUCCESS = 'REMOVE_PERMISSION_FROM_USER_SUCCESS',

  // ?PASSWORD
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  ROLE_CHANGED = 'ROLE_CHANGED',

  // ? ORGANIZATION
  CREATE_ORGANIZATION_FAILED = 'CREATE_ORGANIZATION_FAILED',
  CREATE_ORGANIZATION_SUCCESS = 'CREATE_ORGANIZATION_SUCCESS',
  GET_ORGANIZATION_FAILED = 'GET_ORGANIZATION_FAILED',
  GET_ORGANIZATION_SUCCESS = 'GET_ORGANIZATION_SUCCESS',
  UPDATE_ORGANIZATION_FAILED = 'UPDATE_ORGANIZATION_FAILED',
  UPDATE_ORGANIZATION_SUCCESS = 'UPDATE_ORGANIZATION_SUCCESS',
  DELETE_ORGANIZATION_FAILED = 'DELETE_ORGANIZATION_FAILED',
  DELETE_ORGANIZATION_SUCCESS = 'DELETE_ORGANIZATION_SUCCESS',

  // ? ORGANIZATION MEMBER
  ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS',
  ADD_MEMBER_FAILED = 'ADD_MEMBER_FAILED',
  UPDATE_MEMBER_ROLE_SUCCESS = 'UPDATE_MEMBER_ROLE_SUCCESS',
  UPDATE_MEMBER_ROLE_FAILED = 'UPDATE_MEMBER_ROLE_FAILED',
  REMOVE_MEMBER_SUCCESS = 'REMOVE_MEMBER_SUCCESS',
  REMOVE_MEMBER_FAILED = 'REMOVE_MEMBER_FAILED',
  MEMBER_NOTFOUND = 'MEMBER_NOTFOUND',
  MEMBER_EXIST = 'MEMBER_EXIST',

  // ? PERMISSION
  CREATE_PERMISSION_FAILED = 'CREATE_PERMISSION_FAILED',
  CREATE_PERMISSION_SUCCESS = 'CREATE_PERMISSION_SUCCESS',
  ASSIGN_PERMISSION_TO_ROLE_FAILED = 'ASSIGN_PERMISSION_TO_ROLE_FAILED',
  ASSIGN_PERMISSION_TO_ROLE_SUCCESS = 'ASSIGN_PERMISSION_TO_ROLE_SUCCESS',
  GET_ROLE_PERMISSIONS_FAILED = 'GET_ROLE_PERMISSIONS_FAILED',
  GET_ROLE_PERMISSIONS_SUCCESS = 'GET_ROLE_PERMISSIONS_SUCCESS',
  GET_PERMISSIONS_SUCCESS = 'GET_PERMISSIONS_SUCCESS',
  REMOVE_PERMISSION_FROM_ROLE_FAILED = 'REMOVE_PERMISSION_FROM_ROLE_FAILED',
  REMOVE_PERMISSION_FROM_ROLE_SUCCESS = 'REMOVE_PERMISSION_FROM_ROLE_SUCCESS',
  DELETE_PERMISSION_FAILED = 'DELETE_PERMISSION_FAILED',
  DELETE_PERMISSION_SUCCESS = 'DELETE_PERMISSION_SUCCESS',

  // ?ACCESS
  NOT_ACCESS = 'NOT_ACCESS',
  FORBIDDEN = 'FORBIDDEN',

  // ? Invitation 
  CREATE_INVITATION_SUCCESS='CREATE_INVITATION_SUCCESS',
ACCEPT_INVITATION_SUCCESS='ACCEPT_INVITATION_SUCCESS',
REVOKE_INVITATION_SUCCESS='REVOKE_INVITATION_SUCCESS',

  // ? API
  API_ACCESS = 'API_ACCESS',
}
